### ISSUE TITLE
Error in flutterflow

### ISSUE THREAD

**Issue by aledezma9** [ammaratef45/animated_typing#5]
Error: Failed running flutter pub get...
The current Dart SDK version is 3.0.3.
please help.

**Comment by ammaratef45** [comment]
@aledezma9 can you share the error message?

**Comment by aledezma9** [comment]
Hi, i use flutterflow, and create a custom widget whit your pakage, in the editor on flutterflow, not exist the pagake.
  
Note: this pakage is addeded in te dependendences.
  
Tnks for your help.
  

  

  

  
  
  
  
>

**Comment by aledezma9** [comment]
Sorry my language is Spanish, maybe I do not explain, I want to create a Custom Widget in Flutterflow, use your package, but apparently there is a problem with the version since you do not add it, try with the three versions you have and no works.
  

  

  

  
  
  
  
  
>

**Comment by ammaratef45** [comment]
I'm not familiar with FlutterFlow and not sure how you can use my package with it, I would advise you to check out the help section on their website.

I'll be closing this issue, feel free to open a new one if you have a different question or if you have the full log/error message
